name: statball
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^6.0.1
  google_fonts: ^8.1.0
  hydrated_bloc: ^11.0.0
  path_provider: ^2.1.6
  reactive_forms: ^18.2.2
  routemaster: ^1.1.1
  supabase_flutter: ^2.15.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/
    - assets/fonts/
    - assets/fonts/inter/
    - assets/fonts/monoton/

  # Agrega esta sección específica para las fuentes
  # fonts:
  #   - family: Inter
  #     fonts:
  #       - asset: assets/fonts/inter/Inter_18pt-Thin.ttf
  #         weight: 100
  #       - asset: assets/fonts/inter/Inter_18pt-ExtraLight.ttf
  #         weight: 200
  #       - asset: assets/fonts/inter/Inter_18pt-Light.ttf
  #         weight: 300
  #       - asset: assets/fonts/inter/Inter_18pt-Regular.ttf
  #         weight: 400
  #       - asset: assets/fonts/inter/Inter_18pt-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/inter/Inter_18pt-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/inter/Inter_18pt-Bold.ttf
  #         weight: 700
  #       - asset: assets/fonts/inter/Inter_18pt-ExtraBold.ttf
  #         weight: 800
  #       - asset: assets/fonts/inter/Inter_18pt-Black.ttf
  #         weight: 900